# Generated by Django 5.2.4 on 2025-07-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_options_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={},
        ),
    ]
